#!/usr/bin/env python3
"""Render spec/schema/OBJECT-MODEL.md from the LinkML schema.

A human-readable DRAFT of every object type: a mermaid object↔relation graph and
per-object schema tables + the enums. Regenerate whenever the LinkML changes —
this is the incrementable view of the schema, not a second source of truth.

    python3 spec/schema/render_object_model.py
Deterministic, PyYAML only, no network.
"""
from __future__ import annotations
import datetime as _dt
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("render_object_model: needs PyYAML (pip install pyyaml)")

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "spec" / "schema" / "tmodel-object-model.linkml.yaml"
OUT = ROOT / "spec" / "schema" / "OBJECT-MODEL.md"


def main() -> int:
    d = yaml.safe_load(SRC.read_text())
    classes = d.get("classes", {}) or {}
    slots = d.get("slots", {}) or {}
    enums = d.get("enums", {}) or {}
    class_names = set(classes)
    enum_names = set(enums)

    def slotdef(cls: dict, name: str) -> dict:
        # inline attributes override top-level slot defs
        attrs = (cls.get("attributes") or {})
        return attrs.get(name) or slots.get(name) or {"range": "string"}

    def kind(rng: str) -> str:
        if rng in class_names:
            return "edge"
        if rng in enum_names:
            return "enum"
        return "scalar"

    def class_slots(cname: str, cls: dict) -> list[tuple[str, dict]]:
        names = list(cls.get("slots") or [])
        names += [a for a in (cls.get("attributes") or {}) if a not in names]
        return [(n, slotdef(cls, n)) for n in names]

    out: list[str] = []
    out.append("<!-- GENERATED by spec/schema/render_object_model.py — do not hand-edit; "
               "edit the LinkML and regenerate. -->")
    out.append("# tmodel object model — draft (all object types)\n")
    out.append(f"> **DRAFT, incrementable.** Generated from `{SRC.relative_to(ROOT)}` "
               f"(schema v{d.get('version','?')}, status {d.get('status','?')}) on "
               f"{_dt.date.today().isoformat()}. Regenerate: "
               f"`python3 spec/schema/render_object_model.py`. **Not normative** — DEC-001 "
               f"(object model) and DEC-002 (encoding) are open; this view grows as the "
               f"schema is filled out (RPT-0015 §3/§4).\n")
    out.append(f"**{len(classes)} object types · {len(slots)} slots · {len(enums)} enums.** "
               "Base type `Node` (abstract) gives every object a stable `id` (ADR-0004); "
               "its inheritance edges are omitted from the graph for readability.\n")

    # ---- mermaid relation graph (class->class slot edges + non-Node is_a) ----
    out.append("## Object relation graph\n")
    out.append("```mermaid")
    out.append("classDiagram")
    for cn in sorted(classes):
        out.append(f"  class {cn}")
        if (classes[cn] or {}).get("abstract"):
            out.append(f"  <<abstract>> {cn}")
    for cn in sorted(classes):
        cls = classes[cn] or {}
        parent = cls.get("is_a")
        if parent and parent != "Node":
            out.append(f"  {parent} <|-- {cn}")
        seen = set()
        for sname, sd in class_slots(cn, cls):
            rng = sd.get("range", "")
            if kind(rng) == "edge" and (sname, rng) not in seen:
                seen.add((sname, rng))
                card = ' "*"' if sd.get("multivalued") else ""
                out.append(f"  {cn} -->{card} {rng} : {sname}")
    out.append("```\n")

    # ---- per-object schema tables ----
    out.append("## Object schemas\n")
    for cn in sorted(classes):
        cls = classes[cn] or {}
        bits = []
        if cls.get("is_a"):
            bits.append(f"`is_a: {cls['is_a']}`")
        if cls.get("abstract"):
            bits.append("**abstract**")
        out.append(f"### {cn}" + (f" — {', '.join(bits)}" if bits else ""))
        desc = (cls.get("description") or "").strip()
        if desc:
            out.append(f"\n{desc}\n")
        rows = class_slots(cn, cls)
        if not rows:
            out.append("\n_(no own slots — see gap list in RPT-0015 §4)_\n")
            continue
        out.append("\n| slot | type | req | multi | notes |")
        out.append("|---|---|---|---|---|")
        for sname, sd in rows:
            rng = sd.get("range", "string")
            k = kind(rng)
            typ = (f"→ `{rng}`" if k == "edge" else
                   (f"enum `{rng}`" if k == "enum" else f"`{rng}`"))
            req = "✓" if sd.get("required") else ""
            multi = "✓" if sd.get("multivalued") else ""
            note = re.sub(r"\s+", " ", (sd.get("description") or "")).strip()
            if len(note) > 140:
                note = note[:137] + "…"
            note = note.replace("|", "\\|")
            out.append(f"| `{sname}` | {typ} | {req} | {multi} | {note} |")
        out.append("")

    # ---- enums ----
    out.append("## Enumerations\n")
    for en in sorted(enums):
        pv = (enums[en] or {}).get("permissible_values") or {}
        vals = ", ".join(f"`{v}`" for v in pv) if pv else "_(none listed)_"
        edesc = re.sub(r"\s+", " ", ((enums[en] or {}).get("description") or "")).strip()
        out.append(f"- **{en}**{f' — {edesc}' if edesc else ''}: {vals}")
    out.append("")

    OUT.write_text("\n".join(out))
    print(f"wrote {OUT.relative_to(ROOT)} — {len(classes)} classes, {len(enums)} enums")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
